logging:
  level:
    ROOT: INFO
    io.github.jhipster: INFO
    io.github.jhipster.sample: INFO
management:
  metrics:
    export:
      prometheus:
        enabled: false
spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/jhipsterSampleApplication
    username: root
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  mail:
    host: localhost
    port: 25
    username:
    password:
  thymeleaf:
    cache: true
