#!/bin/bash

regex="^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$"
mail=$(git config --get user.email)

if [ -z "$mail" ]; then
        echo "Git Email is empty. Please set it. Exiting Commit..."
        exit 1
fi

if [[ ! "$mail" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$ ]]; then
        echo "Email Format is not correctly set. Exiting Commit..."
        exit 1
fi
